### ISSUE TITLE
Refused to set unsafe header "user-agent" in Chrome, when using @logdna/logger on Client

### ISSUE THREAD

**Issue by yevhen-logosha** [logdna/logger-node#27]
Hey guys.

Need your help with this guy here..
Got @logdna/logger 2.0.0 setup on Client. Added bits to whitelist, all well and good apart from this error message in Chrome Version 86.0.4240.111 (Official Build) (x86_64):

`Refused to set unsafe header "user-agent"`

It slows down sending the log, some times preventing it from send altogether.. 
Is there something Im missing in config, or how can I address it, please assist.

<img width="632" alt="Screenshot 2020-10-29 at 16 03 55" src="https://user-images.githubusercontent.com/25623699/97584166-67479a00-1a00-11eb-8b96-6c54f00e0285.png">

PS Safari is alright

Many thanks in advance!

**Comment by darinspivey** [comment]
Hi there, thanks for reporting this.  Although `user-agent` is an allowed CORS header, it appears that this version of Chrome is just dropping it altogether.  I think this warrants an addition of a flag which tells the logger that it's running in a browser (we prefer to be explicit rather than check for the existence of `window`), and if present, the user-agent header is not sent at all.

Stay tuned while we open an issue and get to to work on it!

**Comment by darinspivey** [comment]
There's good news and bad news with this one.  First, the bad.

We use `axios` as the HTTP agent so that it plays nice in a browser (we obviously want that flexibility for our customers).  The problem is that axios forces a `user-agent` header if one isn't provided.  We attempted to omit the header, but integration tests show that it's still being set to `axios/x.x.x` and therefore does not solve the problem.  This issue is compounded by the fact that there are not a lot of XHR request packages out there for node, and switching one would be somewhat of a risky change anyway.  Axios also currently has 61 open PRs and almost 200 issues, so it's not likely we could effect change by submitting a fix of our own.

The good news is that the payload should still be sending, despite the chattery console error you're seeing.  The community has confirmed not only this issue with the headers in certain browsers, but also that it should still work to send the payload.  Can you confirm that the log entries are showing up otherwise?

We're sorry we don't have the magic fix at this time, but we definitely tried.  Let us know what you find out with your log entries still making it to LogDNA.  Thanks.

**Comment by darinspivey** [comment]
Apologies, we spoke too soon!  The `axios` code that unconditionally sets the `user-agent` header exists in their http transport, but NOT the xhr transport.  Once we realized this, we bundled our new changes and tested them directly in a browser and discovered that it works just fine.  Our test suite will not be able to test using the xhr transport, but coverage can still be at 100%.

The PR will be opened shortly, then afterwards, you'll be able to instantiate the logger with `sendUserAgent: false`, and that will omit the user-agent header and silence the error you are seeing.

**Comment by yevhen-logosha** [comment]
@darinspivey Hey mate. 
Thank you for your time investigating this. My bad, logs are getting to LogDNA with payload, must have hit some delay, but eventually they shown up. Apologies for confusion! 
Look forward to `sendUserAgent`! You guys rock 🎸

**Comment by darinspivey** [comment]
No worries at all!  It certainly feels like a hard error, so better for us to get out of the browser's way in those cases.
